name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  record: ^6.0.0
  path_provider: ^2.1.2
  just_audio: ^0.10.4
  google_maps_flutter: ^2.5.0
  latlong2: ^0.9.1
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  uuid: ^4.0.0
  file_selector: ^0.9.0
  ffmpeg_kit_flutter_full_gpl: ^4.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env